baseURL: "https://www.wsyuacm.com/"
title: æ­¦æ˜Œé¦–ä¹‰å­¦é™¢ ACMçˆ±å¥½è€…åä¼š
paginate: 5
theme: PaperMod

copyright: "**Â©&nbsp;2019-2022&nbsp;&nbsp;[æ­¦æ˜Œé¦–ä¹‰å­¦é™¢ ACMçˆ±å¥½è€…åä¼š](https://www.wsyuacm.com/) ï½œ [é„‚ICPå¤‡19011794å·](https://beian.miit.gov.cn/)**"
enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
defaultContentLanguage: zh

minify:
    disableXML: true
    minifyOutput: true

languages:
    zh:
        languageName: "ä¸­æ–‡"
        weight: 2
        title: "æ­¦æ˜Œé¦–ä¹‰å­¦é™¢ ACMçˆ±å¥½è€…åä¼š"
        taxonomies:
          category: åˆ†ç±»
          tag: æ ‡ç­¾
        profileMode:
          enabled: true
          title: "ACMçˆ±å¥½è€…åä¼š"
          subtitle: "è¿™é‡Œæ˜¯æ­¦æ˜Œé¦–ä¹‰å­¦é™¢ACMçˆ±å¥½è€…åä¼šï¼Œæ˜¯å¯¹äºç«èµ›æ€§ç¼–ç¨‹ï¼ˆCompetitive Programmingï¼‰æœ‰ç€æµ“éƒå…´è¶£çš„å›¢ä½“ã€‚ ğŸŒ™ "
          buttons:
              - name: æ–‡ç« 
                url: posts/
              - name: OJç³»ç»Ÿ
                url: "https://oj.wsyuacm.com/"
        menu:
            main:
                - name: æ–‡ç« 
                  url: posts/
                  weight: 5
                - name: åä¼šç›¸å†Œ
                  url: posts/gallery/
                  weight: 10
                - name: è£èª‰å¥–é¡¹
                  url: posts/honorary-awards/
                  weight: 15
                - name: å›¢é˜Ÿç»„æˆ
                  url: posts/team-composition/
                  weight: 20
                - name: æ‰¿åŠæ´»åŠ¨
                  url: posts/hosting-events/
                  weight: 25
                - name: åä¼šä»‹ç»
                  url: posts/introduce/
                  weight: 30

    en:
        languageName: "English"
        weight: 1
        title: ACM Club of WSYU
        taxonomies:
          category: ENcategories
          tag: ENtags
        profileMode:
          enabled: true
          title: Association for Computing Machinery Club
          subtitle: "Hi there, This is ACM Club of WSYU, is a computer science society and WSYU tech enthusiasts hub dedicated to providing unique opportunities, mentoring and support for passionate WSYU students majoring in Computer Science or Computer Engineering. ğŸŒ™ "
          buttons:
              - name: Blog
                url: /posts/
              - name: Online Judge
                url: "https://oj.wsyuacm.com/"
        menu:
            main:
                - name: Post
                  url: ../posts/
                  weight: 5
                - name: Gallery
                  url: ../posts/gallery/
                  weight: 10
                - name: Honorary
                  url: ../posts/honorary-awards/
                  weight: 15
                - name: Team
                  url: ../posts/team-composition/
                  weight: 20
                - name: Events
                  url: ../posts/hosting-events/
                  weight: 25
                - name: Introduce
                  url: ../posts/introduce/
                  weight: 30
outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production
    description: "è¿™é‡Œæ˜¯æ­¦æ˜Œé¦–ä¹‰å­¦é™¢ACMçˆ±å¥½è€…åä¼šï¼Œæ˜¯å¯¹äºç«èµ›æ€§ç¼–ç¨‹ï¼ˆCompetitive Programmingï¼‰æœ‰ç€æµ“éƒçˆ±å¥½çš„å›¢ä½“ã€‚"
    # author: "æ­¦æ˜Œé¦–ä¹‰å­¦é™¢ ACMçˆ±å¥½è€…åä¼š"

    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    # disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: true
    ShowToc: true
    # comments: false
    images: [""]
    
    socialIcons:
        # - name: github
        #   url: "https://github.com/adityatelange/hugo-PaperMod"
        # - name: KoFi
        #   url: "https://ko-fi.com/adityatelange"
        # - name: Discord
        #   url: "https://discord.gg/ahpmTvhVmp"
        - name: RsS
          url: "index.xml"

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        noClasses: false
        # anchorLineNos: true
        # codeFences: true
        # guessSyntax: true
        # lineNos: true
        # style: monokai

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true
